# Configure a default setup of Home Assistant (frontend, api, etc)
logger:
  default: debug
  logs:
    custom_components.school: info

default_config:
python_script:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml

homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
      trusted_users:
        192.168.0.0/16:
          - f1a0d51bf81a474b846ab33537af3496
          - e6ead2ebf33f45508df3c592e06292d7

tts:
  - platform: google_translate

switch:
  - platform: mqtt
    name: "Ventilator"
    state_topic: "shellies/shelly1/relay/0"
    command_topic: "shellies/shelly1/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: false

panel_iframe:
  weather:
    title: "Weather"
    url: "https://embed.windy.com/embed2.html?lat=49.668&lon=15.447&zoom=7&level=surface&overlay=wind&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=50.082&detailLon=14.425&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1"
    icon: mdi:weather-windy

sonoff:
  username: !secret default_username
  password: !secret default_password
   
vacuum:
  - platform: xiaomi_miio
    host: !secret ip_vacuum
    token: !secret mi_token

#camera:
#  - platform: xiaomi_cloud_map_extractor
#    host: !secret ip_vacuum
#    token: !secret mi_token
#    username: !secret default_username
#    password: !secret default_password
#    draw: ['all']
#    attributes:
#      - calibration_points  

notify:
  - platform: pushover
    name: Pusher
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

input_boolean:
  enable_daily_vacuum:
    name: Daily cleanup
  enable_automatic_ventilation:
    name: Automatic

input_datetime:
  last_cleanup_time:
    name: Last time of clean up
    has_date: true
    has_time: true

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select ...
      - Bedroom
      - Living room
      - Kids room
      - Kitchen
      - Hall

recorder:
  db_url: mysql://root:pi@127.0.0.1:3306/homeassistant?charset=utf8
  purge_keep_days: 7
  commit_interval: 60
  include:
    entities:
      - sensor.sht31_temperature
      - sensor.sht31_humidity
      - sensor.mh_z19_co2
    entity_globs:
      - person.*

influxdb:
  host: !secret ip_hass
  port: 8086
  include:
    entities:
       - sensor.mh_z19_co2
       - sensor.sht31_temperature
       - sensor.sht31_humidity
       - sensor.siemens_ag
       - sensor.eur_czk
       - sensor.waqi_pha10_prumyslova_prague_czech_republic
       - sensor.temperature_6
       - sensor.fgsd002_smoke_sensor_air_temperature
       - sensor.bathroom_temperature

octoprint:
  - host: !secret ip_octoprint
    api_key: !secret octoprint_api_key
    name: Ender3 V2
    number_of_tools: 1
    bed: True

wake_on_lan:
 
webostv:
  host: !secret ip_tv
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_tv
      broadcast_address: 192.168.11.255
  customize:
    sources:
      - hdmi1
      - 'SledovaniTV 2.0'
      - Youtube
      - Netflix