- platform: time_date
  display_options:
    - "date"
    - "time"
    - "date_time"
- platform: template
  sensors:
    days_since_last_cleanup:
      friendly_name: Days ago
      value_template: "{{ ((as_timestamp(now())-(states.input_datetime.last_cleanup_time.attributes.timestamp)) | int /86400) | round(1) }}"
      unit_of_measurement: "Days"
- platform: template
  sensors:
    vacuum_status:
      friendly_name: Status
      value_template: "Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"
      icon_template: >
        {% set val =  states.vacuum.xiaomi_vacuum_cleaner.attributes.status  %}
        {% if val == 'Charging' %}
          mdi:battery-charging
        {% elif val == 'Cleaning' %}
          mdi:move-resize
        {% elif val == 'Returning home' %}
          mdi:keyboard-return
        {% elif val == 'Idle' %}
          mdi:dots-horizontal
        {% elif val == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_error:
      friendly_name: Vacuum Cleaner Error
      value_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
          {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
        {% else %}
          No Error
        {% endif %}
    vacuum_fan_speed:
      friendly_name: Fan Speed
      value_template: "Mode: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}"
      icon_template: "mdi:speedometer"
    vacuum_battery:
      friendly_name: Vacuum Battery
      value_template: "Battery: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}"
      unit_of_measurement: "%"
      icon_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}"
    vacuum_cleaning_time:
      friendly_name: Time of Last Cycle
      value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}"
      icon_template: "mdi:timer"
    vacuum_cleaned_area:
      friendly_name: Area of Last Cycle
      unit_of_measurement: "m2"
      value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}"
      icon_template: "mdi:ruler"
    vacuum_cleanmainbrush:
      friendly_name: Replace main brush
      unit_of_measurement: "h"
      value_template: "Main Brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}"
      icon_template: "mdi:screwdriver"
    vacuum_cleansidebrush:
      friendly_name: Replace side brush
      unit_of_measurement: "h"
      value_template: "Side brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}"
      icon_template: "mdi:screwdriver"
    vacuum_cleanfilter:
      friendly_name: Replace filter
      unit_of_measurement: "h"
      value_template: "Filter: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}"
      icon_template: "mdi:screwdriver"
    vacuum_sensordirtyleft:
      friendly_name: Replace filter
      unit_of_measurement: "h"
      value_template: "Sensor: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}"
      icon_template: "mdi:screwdriver"
- platform: waze_travel_time
  origin: !secret waze_origin
  destination: !secret waze_destination
  region: 'EU'
  name: "Travel time to work"
- platform: waqi
  token: !secret waqi_token
  locations:
    - pha10-prumyslova
- platform: alpha_vantage
  api_key: !secret alpha_vantage_api_key
  foreign_exchange:
    - name: EUR_CZK
      from: EUR
      to: CZK
- platform: stock_price
  api_key: !secret alpha_vantage_api_key
  symbols:
    - symbol: SIE.DEX
      currency: EUR
      name: Siemens AG
# Home Assistant
- platform: version
  name: latest_version_homeassistant
  source: docker
  beta: true
- platform: version
  name: current_version_homeassistant
#OctoPrint
- platform: template
  sensors:
    octoprint_time_elapsed:
      friendly_name: 'Printing Time Elapsed'
      value_template: "{{ states('sensor.ender3_v2_time_elapsed') | int | timestamp_custom('%H:%M:%S', 0) }}"
    octoprint_time_remaining:
      friendly_name: 'Printing Time Remaining'
      value_template: "{{ states('sensor.ender3_v2_time_remaining') | int | timestamp_custom('%H:%M:%S', 0) }}"
#Weather
- platform: template
  sensors:
    temperature_out:
      friendly_name: 'Temperature'
      value_template: "{{ state_attr('weather.domov', 'temperature') }}"
      unit_of_measurement: "°C"
    humidity_out:
      friendly_name: 'Humidity'
      value_template: "{{ state_attr('weather.domov', 'humidity') }}"
      unit_of_measurement: "%"
    pressure_out:
      friendly_name: 'Pressure'
      value_template: "{{ state_attr('weather.domov', 'pressure') }}"
      unit_of_measurement: "hPa"
    wind_out:
      friendly_name: 'Wind speed'
      value_template: "{{ state_attr('weather.domov', 'wind_speed') }}"
      unit_of_measurement: "km/h"
    bathroom_temperature:
      value_template: "{{ state_attr('binary_sensor.water_sensor', 'temperature') }}"
      unit_of_measurement: "°C"