- platform: time_date
  display_options:
    - "date"
    - "time"
    - "date_time"
- platform: template
  sensors:
    days_since_last_cleanup:
      friendly_name: Days ago
      value_template: "{{ ((as_timestamp(now())-(states.input_datetime.last_cleanup_time.attributes.timestamp)) | int /86400) | round(1) }}"
      unit_of_measurement: "Days"
- platform: template
  sensors:
    vacuum_status:
      friendly_name: Status
      value_template: "Status: {{ states.vacuum.mi_robot_vacuum.attributes.status }}"
      icon_template: >
        {% set val =  states.vacuum.mi_robot_vacuum.attributes.status  %}
        {% if val == 'Charging' %}
          mdi:battery-charging
        {% elif val == 'Cleaning' %}
          mdi:move-resize
        {% elif val == 'Returning home' %}
          mdi:keyboard-return
        {% elif val == 'Idle' %}
          mdi:dots-horizontal
        {% elif val == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_error:
      friendly_name: Vacuum Cleaner Error
      value_template: >-
        {% if states.vacuum.mi_robot_vacuum.attributes.error is defined %}
          {{states.vacuum.mi_robot_vacuum.attributes.error}}
        {% else %}
          No Error
        {% endif %}
    vacuum_fan_speed:
      friendly_name: Fan Speed
      value_template: "Mode: {{ states.vacuum.mi_robot_vacuum.attributes.fan_speed }}"
      icon_template: "mdi:speedometer"
    vacuum_battery:
      friendly_name: Vacuum Battery
      value_template: "Battery: {{ states.vacuum.mi_robot_vacuum.attributes.battery_level }}"
      unit_of_measurement: "%"
      icon_template: "{{ states.vacuum.mi_robot_vacuum.attributes.battery_icon }}"
#Stocks
- platform: alpha_vantage
  api_key: !secret alpha_vantage_api_key
  foreign_exchange:
    - name: EUR_CZK
      from: EUR
      to: CZK
- platform: stock_price
  api_key: !secret alpha_vantage_api_key
  symbols:
    - symbol: SIE.DEX
      currency: EUR
      name: Siemens AG
#Home Assistant
- platform: version
  name: latest_version_homeassistant
  source: container
  beta: false
  image: raspberrypi4
- platform: version
  name: current_version_homeassistant
#Weather
- platform: template
  sensors:
    bathroom_temperature:
      value_template: "{{ state_attr('binary_sensor.water_sensor', 'temperature') }}"
      unit_of_measurement: "°C"
#Steam
#- platform: steam_online
#  api_key: !secret steam_api_key
#  accounts:
#    - 76561198254663953
# SystemMonitor
- platform: systemmonitor
  resources:
  - type: disk_use_percent
  - type: disk_use
  - type: disk_free
  - type: memory_free
  - type: memory_use
  - type: memory_use_percent
  - type: throughput_network_in
    arg: eth0
  - type: throughput_network_out
    arg: eth0
  - type: ipv4_address
    arg: eth0
  - type: processor_use
  - type: last_boot
- platform: command_line
  name: processor_temp
  command: "cat /thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  scan_interval: 300
  value_template: "{{ value | multiply(0.001) | round(1) }}"